name: 'Zip-And-Publish-Release'

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Modpack Version. Example: 0.5.6'
        required: true
      release-type:
        type: choice
        required: true
        description: 'Alpha, Beta, Release'
        options:
          - 'Alpha'
          - 'Beta'
          - 'Release'
env:
  MODPACK_VERSION: ${{ github.event.inputs.version }}
  RELEASE_TYPE: ${{ github.event.inputs.release-type }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-zip:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print version and release type
        run: |
          echo "MODPACK_VERSION: ${{ env.MODPACK_VERSION }}"
          echo "RELEASE TYPE: ${{ env.RELEASE_TYPE }}"
      - name: Create zip
        uses: vimtor/action-zip@v1
        with:
          files: overrides manifest.json modlist.html
          recursive: false
          dest: GFLCraft-v${{ env.MODPACK_VERSION }}-${{ github.event.inputs.release-type }}.zip
      - name: Upload zip to Artifact
        uses: actions/upload-artifact@v1
        with:
          name: gflcraft-artifact
          path: ${{ github.workspace }}/GFLCraft-v${{ env.MODPACK_VERSION }}-${{ github.event.inputs.release-type }}.zip
      
          
#      - name: Push tag
#        uses: laputansoft/github-tag-action@v4.6
#        id: push_tag
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          tag: gflcraft-v${{ env.MODPACK_VERSION }}
#      - name: Print outputs from tag push
#        run: |
#          echo "new_tag: ${{ steps.push_tag.outputs.new_tag }}"
#          echo "latest_hash: ${{ steps.push_tag.outputs.latest_hash }}"
#          echo "previous_tag: ${{ steps.push_tag.outputs.previous_tag }}"
#          echo "changelog: ${{ steps.push_tag.outputs.changelog }}"
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/GFLCraft-v${{ env.MODPACK_VERSION }}-${{ github.event.inputs.release-type }}.zip"
          bodyFile: "CHANGELOG.md"
          tag: "gflcraft-v${{ env.MODPACK_VERSION }}"
          commit: "main"
#      - name: release
#        uses: actions/create-release@v1
#        id: create_release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          draft: false
#          prerelease: false
#          release_name: GFLCraft-v${{ env.MODPACK_VERSION }}
#          tag_name: release-${{ github.sha }}
#          body_path: CHANGELOG.md
       # env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload zip to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/GFLCraft-v${{ env.MODPACK_VERSION }}-${{ github.event.inputs.release-type }}.zip
          asset_name: GFLCraft-v${{ env.MODPACK_VERSION }}-${{ github.event.inputs.release-type }}.zip
          asset_content_type: application/zip
          
      
